# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
        - "27017:27017"    

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]

  gxweb:
    image: rameshkumarcd/gxweb
    ports:
        - "8000:80"
        - "44348:443"
    depends_on:
        - mongo
    links:
      - mongo
